language: cpp
git:
  depth: 1
script:
  - bash scripts/$TRAVIS_OS_NAME/build.sh
matrix:
  include:
  - os: linux
    compiler: gcc
    dist: bionic
    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install devscripts build-essential
      - sudo apt-get install qtdeclarative5-dev qt5-default
