language: cpp
git:
  depth: 3
matrix:
  include:
#  - os: linux
#    compiler: gcc
#    dist: bionic
#    before_install:
#      - sudo apt-get update -qq
#      - sudo apt-get install devscripts build-essential
#      - sudo apt-get install qtdeclarative5-dev qt5-default
#    script:
#        - bash scripts/ci/$TRAVIS_OS_NAME/build.sh
#  - os: osx
#    compiler: clang
#    before_install:
#        - brew install qt5
#        - brew link qt5 --force
#    script:
#        - bash scripts/ci/$TRAVIS_OS_NAME/build.sh
  - os: windows
        before_install:
           - cmd.exe /C 'cd && "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvars32.bat"'
           - curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
           - "./qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs"
        script:
           - cmd.exe /C 'cd && "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvars32.bat" && cd && "C:/Qt/5.12.3/msvc2017/bin/qmake" DockingPanes.pro && cd && nmake'
           - ls
           